version: '3.8'
services:

  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

  locust:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: locust
    hostname: locust
    ports:
      - 8089:8089
    depends_on:
      - clickhouse
