version: "3.8"
services:
  ugc_api:
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      redis_ugc:
        condition: service_started
    expose:
      - 8000
    container_name: ugc_api

  redis_ugc:
    image: redis:latest
    volumes:
      - redis_ugc_data:/data:rw
    command: >
      --save 60 1
    expose:
      - 6379
    ports:
      - 6379:6379
    container_name: redis_ugc

  nginx_ugc:
    image: nginx:1.23.3
    restart: unless-stopped
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - sprint08_ugc_api_static:/static:ro
    depends_on:
      - ugc_api
    ports:
      - 89:80
    container_name: nginx_ugc

volumes:
  redis_ugc_data:
  sprint08_ugc_api_static: