version: "3.8"
services:
  ugc_api:
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      redis_ugc:
        condition: service_started
    expose:
      - 8000
    container_name: ugc_api

  redis_ugc:
    image: redis:latest
    volumes:
      - redis_ugc_data:/data:rw
    command: >
      --save 60 1
    expose:
      - 6379
    ports:
      - 6379:6379
    container_name: redis_ugc

volumes:
  redis_ugc_data: