version: "3.8"
services:
  ugc_api:
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file:
      - ./.env
#    depends_on:
#      redis_cache:
#        condition: service_started
    expose:
      - 8000
    container_name: ugc_api
