repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: double-quote-string-fixer

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      # exclude: (migrations|alembic/versions/)
      args: [--profile, black, --line-length=120]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
    - id: bandit

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      # exclude: (migrations|config/settings/|alembic/versions/)
      args: [--line-length=120]

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      name: flake8
      entry: 'flake8 --config=setup.cfg'
      language: python
      additional_dependencies:
        - flake8-docstrings
