version: '3.8'
services:
  clickhouse:
    build: ./
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - kafka-ch
    env_file:
      - ../ugc_api/.env
networks:
  kafka-ch:
    name: kafka-ch
