version: '3.8'
services:
  clickhouse:
    build: ./
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - microservice-network
    env_file:
      - ../ugc_api/.env
networks:
  microservice-network:
    name: microservice-network
