version: '3.8'
services:

  locust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locust_cs
    hostname: locust_cs
    volumes:
      - ./load_test_insert_cs.py:/app/load_test_insert_cs.py
      - ./load_test_query_cs.py:/app/load_test_query_cs.py
    tty: true
    ports:
      - 8089:8089

  node1:
      image: datastax/dse-server:6.8.16-ubi7
      container_name: DSE-6_node1
      hostname: node1
      # use static ip address
      # networks:
      #     dc1ring:
      #         ipv4_address: 172.30.0.2
      volumes:
          - ugcdb:/opt/dse/ugcdb
      environment:
          - DS_LICENSE=accept
          - SEEDS=node1
          - START_RPC=false
          - CLUSTER_NAME=dse51_cluster
          - NUM_TOKENS=3
          - DC=DC1
          - RACK=RAC1
          - MAX_HEAP_SIZE=1000000000
      expose:
          # Intra-node communication
          - 7000
          # TLS intra-node communication
          - 7001
          # JMX
          - 7199
          # CQL
          - 9042
          # CQL SSL
          - 9142
      ports:
          - 9042:9042
      ulimits:
          memlock: -1
          nproc: 32768
          nofile: 100000
  node2:
      image: datastax/dse-server:6.8.16-ubi7
      container_name: DSE-6_node2
      hostname: node2
      # networks:
      #     dc1ring:
      #         ipv4_address: 172.30.0.3
      volumes:
          - ugcdb:/opt/dse/ugcdb
      environment:
          - DS_LICENSE=accept
          - SEEDS=node1
          - START_RPC=false
          - CLUSTER_NAME=dse51_cluster
          - NUM_TOKENS=3
          - DC=DC2
          - RACK=RAC1
          - MAX_HEAP_SIZE=1000000000
      expose:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9142
      ports:
          - 9043:9042
      ulimits:
          memlock: -1
          nproc: 32768
          nofile: 100000
      depends_on:
          - node1
  node3:
      image: datastax/dse-server:6.8.16-ubi7
      container_name: DSE-6_node3
      hostname: node3
      # networks:
          # dc1ring:
          #     ipv4_address: 172.30.0.4
      volumes:
          - ugcdb:/opt/dse/ugcdb
      environment:
          - DS_LICENSE=accept
          - SEEDS=node1
          - START_RPC=false
          - CLUSTER_NAME=dse51_cluster
          - NUM_TOKENS=3
          - DC=DC1
          - RACK=RAC1
          - MAX_HEAP_SIZE=1000000000
      expose:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9142
      ports:
          - 9044:9042
      ulimits:
          memlock: -1
          nproc: 32768
          nofile: 100000
      depends_on:
          - node1
# networks:
#     dc1ring:
#         ipam:
#             driver: default
#             config:
#                 - subnet: 172.30.0.0/16

volumes:
  ugcdb:
