version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ugc-network
  broker:
    image: confluentinc/cp-kafka:5.3.1
    container_name: broker
    hostname: broker
    ports:
    - "9092:9092"
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092, INT://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://:9092, INT://:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
    - zookeeper
    networks:
      - ugc-network
networks:
  ugc-network:
    name: ugc-network